# This is a minimal Alacritty configuration file in TOML format.
#
# Save this file at: ~/.config/alacritty/alacritty.toml

[font]
# Font size (in points)
size = 12.0

# Normal font face
[font.normal]
# The font family to use. "Fira Code" must be installed on your system.
family = "Fira Code"
style = "Regular"

# Bold font face
[font.bold]
family = "Fira Code"
style = "Bold"

# Italic font face
[font.italic]
family = "Fira Code"
style = "Italic"

# Colors (Alabaster Dark)
# author tonsky

[colors.primary]
background = '#DAD8C9'
foreground = '#1405b0'

[colors.cursor]
text = '#F7F7F7'
cursor = '#b00505'

[colors.normal]
black = '#000000'
red = '#AA3731'
green = '#448C27'
yellow = '#CB9000'
blue = '#325CC0'
magenta = '#7A3E9D'
cyan = '#0083B2'
white = '#BBBBBB'

[colors.bright]
black = '#777777'
red = '#F05050'
green = '#60CB00'
yellow = '#FFBC5D'
blue = '#007ACC'
magenta = '#E64CE6'
cyan = '#00AACB'
white = '#FFFFFF'
